"""Creacion de tablas iniciales SmartStock

Revision ID: af7ef65cb620
Revises: 
Create Date: 2026-07-18 23:26:09.812144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7ef65cb620'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    op.create_index(op.f('ix_categorias_categoria_id'), 'categorias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('clientes',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_index(op.f('ix_clientes_cliente_id'), 'clientes', ['cliente_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('proveedor_id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_proveedores_proveedor_id'), 'proveedores', ['proveedor_id'], unique=False)
    op.create_table('roles',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_rol_id'), 'roles', ['rol_id'], unique=False)
    op.create_table('productos',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('precio_compra >= 0', name='ck_precio_compra_no_negativo'),
    sa.CheckConstraint('precio_venta >= 0', name='ck_precio_venta_no_negativo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.categoria_id'], ),
    sa.PrimaryKeyConstraint('producto_id')
    )
    op.create_index(op.f('ix_productos_producto_id'), 'productos', ['producto_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.create_table('compras',
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.proveedor_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('compra_id')
    )
    op.create_index(op.f('ix_compras_compra_id'), 'compras', ['compra_id'], unique=False)
    op.create_table('inventario',
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.PrimaryKeyConstraint('inventario_id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_index(op.f('ix_inventario_inventario_id'), 'inventario', ['inventario_id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=20), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tipo_movimiento IN ('entrada', 'salida')", name='ck_tipo_movimiento'),
    sa.CheckConstraint('cantidad > 0', name='ck_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('movimiento_id')
    )
    op.create_index(op.f('ix_movimientos_inventario_movimiento_id'), 'movimientos_inventario', ['movimiento_id'], unique=False)
    op.create_table('producto_proveedor',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio_proveedor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.proveedor_id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'proveedor_id')
    )
    op.create_table('ventas',
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('venta_id')
    )
    op.create_index(op.f('ix_ventas_venta_id'), 'ventas', ['venta_id'], unique=False)
    op.create_table('detalle_compra',
    sa.Column('detalle_compra_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_detalle_compra_cantidad_positiva'),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.compra_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.PrimaryKeyConstraint('detalle_compra_id')
    )
    op.create_index(op.f('ix_detalle_compra_detalle_compra_id'), 'detalle_compra', ['detalle_compra_id'], unique=False)
    op.create_table('detalle_venta',
    sa.Column('detalle_venta_id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_detalle_venta_cantidad_positiva'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.venta_id'], ),
    sa.PrimaryKeyConstraint('detalle_venta_id')
    )
    op.create_index(op.f('ix_detalle_venta_detalle_venta_id'), 'detalle_venta', ['detalle_venta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_venta_detalle_venta_id'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    op.drop_index(op.f('ix_detalle_compra_detalle_compra_id'), table_name='detalle_compra')
    op.drop_table('detalle_compra')
    op.drop_index(op.f('ix_ventas_venta_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_table('producto_proveedor')
    op.drop_index(op.f('ix_movimientos_inventario_movimiento_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_inventario_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_compras_compra_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_producto_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_roles_rol_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_proveedores_proveedor_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_clientes_cliente_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_categoria_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
